apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
#  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: phx.ocir.io/intcgbuconsulting/nginx:latest
        ports:
        - name: nginxport
          containerPort: 80
