apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
#  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: brmdb
  replicas: 1
  template:
    metadata:
      labels:
        app: brmdb
    spec:
      containers:
      - name: web
        image: phx.ocir.io/intcgbuconsulting/nginx:BUILDNUMBER
        ports:
        - name: nginxport
          containerPort: 80
